# Generated by Django 4.2.30 on 2026-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check this to display on the homepage'),
        ),
    ]
